using System;
using System.Runtime.InteropServices;
using Cda.Core.Cpu;

namespace Cda.Core.Engine
{
    /// <summary>
    /// Deterministic, in-process validation of the hook codegen — no target
    /// process involved. It writes a tiny native function that returns a known
    /// value, installs a detour that returns a different value, and checks that
    /// the redirect takes effect and that removal restores the original.
    ///
    /// This isolates the dangerous part (machine-code generation: patch sizing,
    /// stolen-byte relocation, jump encoding) from cross-process injection. If
    /// the generated bytes are wrong, the failure happens here, in our own
    /// process, on a throwaway stub — not inside someone else's program.
    ///
    /// WARNING: a codegen bug here can corrupt control flow and crash the app
    /// (an access violation is not a catchable .NET exception). That crash IS
    /// the signal that the byte emission needs fixing.
    /// </summary>
    public static class HookSelfTest
    {
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        private delegate int IntFunc();

        public static string Run()
        {
            var mem = new LocalCodeMemory();
            var arch = CpuArchitectures.For(mem.Is64Bit);

            // Original: mov eax, 0x11111111 ; ret  (padded with NOPs so there is
            // room for a 14-byte x64 detour without clobbering past the region).
            ulong original = mem.Allocate(64, executable: true);
            byte[] origCode = new byte[64];
            WriteMovEaxRet(origCode, 0, 0x11111111);
            for (int i = 6; i < origCode.Length; i++) origCode[i] = 0x90;
            mem.Write(original, origCode);
            mem.Flush(original, origCode.Length);

            // Detour: mov eax, 0x22222222 ; ret
            ulong detour = mem.Allocate(16, executable: true);
            byte[] detourCode = new byte[16];
            WriteMovEaxRet(detourCode, 0, 0x22222222);
            mem.Write(detour, detourCode);
            mem.Flush(detour, detourCode.Length);

            var fn = Marshal.GetDelegateForFunctionPointer<IntFunc>((IntPtr)unchecked((long)original));

            int before = fn();
            if (before != 0x11111111)
                return $"FAIL: baseline returned 0x{before:X}, expected 0x11111111.";

            InlineHook hook;
            try
            {
                hook = InlineHook.Install(arch, mem, original, detour);
            }
            catch (Exception ex)
            {
                return "FAIL: hook install threw — " + ex.Message;
            }

            int hooked = fn();
            int afterRemove;
            hook.Remove();
            afterRemove = fn();

            GC.KeepAlive(fn);

            if (hooked != 0x22222222)
                return $"FAIL: hooked call returned 0x{hooked:X}, expected 0x22222222 (detour not taken).";
            if (afterRemove != 0x11111111)
                return $"FAIL: after Remove returned 0x{afterRemove:X}, expected 0x11111111 (restore failed).";

            return $"PASS ({arch.Name}): baseline=0x{before:X}, hooked=0x{hooked:X}, " +
                   $"restored=0x{afterRemove:X}, patch={hook.PatchLength} bytes, trampoline=0x{hook.Trampoline:X}.";
        }

        // mov eax, imm32 (B8 id) ; ret (C3)
        private static void WriteMovEaxRet(byte[] buf, int offset, uint value)
        {
            buf[offset] = 0xB8;
            buf[offset + 1] = (byte)value;
            buf[offset + 2] = (byte)(value >> 8);
            buf[offset + 3] = (byte)(value >> 16);
            buf[offset + 4] = (byte)(value >> 24);
            buf[offset + 5] = 0xC3;
        }
    }
}
